### ISSUE TITLE
UserJS version

### ISSUE THREAD

**Issue by lollox** [Christoph142/Select-like-a-Boss#3]
As in title, is it possible an userjs version? I prefer userjs since I can handle lot of features with a single process (violentmonkey) while extensions use instead a process for every feature you add in the browser

Thanks in advance :)

**Comment by Christoph142** [comment]
You underestimate the power of Chrome's extension system. This extension does not use a process of its own. I even doubt you'll save **any** resources by using this as a userjs in violentmonkey over using it as an extension.

That said, you should be able to use https://github.com/Christoph142/Select-like-a-Boss/blob/master/extension/script.js without any modifications. ;)

**Comment by lollox** [comment]
I already use some userjs, so I prefer adding other scripts instead of extensions ;)

However I installed the script and it seems to work very good. Until now I had two alternatives:
- the "Selectable Hyperlink Text" (no more available but I have the .crx) extension that breaks HumbleBundle and some other sites
- the "LinkDragSelectionForChrome" userjs that somewhat breaks InoReader (so I disabled the script on that site)

Now it seems I solved all problems with your script, thanks in advance :)
