### ISSUE TITLE
[INVALID] Surrounding items are mistakenly selected

### ISSUE THREAD

**Issue by sergeevabc** [Christoph142/Select-like-a-Boss#4]
Dear @Christoph142, there are popular kanban-style task management service [Trello](https://trello.com/) and mind mapping service [Mindomo](https://www.mindomo.com/), both of them use mouse extensively to manipulate items, either to move cards between columns or nodes between trees. With Select-like-a-boss turned on, such movements mistakenly select surrounding items like someone pressed Ctrl+A. Since this behaviour is annoying, I’m here to ask about fix. Would you care?

- [proof 1](https://ukaz.cz/a/1477961579_7865817e76bb4f8a.png) 
- [proof 2](https://ukaz.cz/a/1477961742_475817e80e5f032.png)

**Comment by Christoph142** [comment]
I see no such issue whatsoever. Are you using this extension or the one from the Chrome Web Store?

**Comment by sergeevabc** [comment]
Thanks for a quick reply, @Christoph142, even though it brings no relief.
Speech is about [extension](https://addons.mozilla.org/en-US/firefox/addon/select-like-a-boss/) for Firefox. Watch [this screencast](https://a.rokket.space/rxjylv.mp4), please.

**Comment by Christoph142** [comment]
I do not have any extension for FF. This is Chromium only. You're texting the wrong guy. ;)

**Comment by lollox** [comment]
To be honest, I use your script (converted in a common userjs) in FF too and it works very well ;)

**Comment by sergeevabc** [comment]
@lollox, check native userjs “[Select text inside a link like Opera][1]”, it is free from the aforesaid drawbacks.

[1]: https://greasyfork.org/en/scripts/789-select-text-inside-a-link-like-opera

**Comment by lollox** [comment]
@sergeevabc , if I recall correctly, that one breaks InoReader ... the one developed by Christoph142 is the only one that doesn't break any of the sites I use
